name: Matrix Configuration

on:
    push: 
    workflow_dispatch: 

jobs:
    deploy-on-multi-platforms:
        strategy:
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, ubuntu-24.04, windows-latest]
                images: [hello-world, alpine]
                exclude:
                    - os: windows-latest
                      images: alpine
                include:
                    - os: ubuntu-latest
                      images: amd64/alpine
        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo docker details
              run: docker info

            - name: Run images on ${ matrix.os }}
              run: docker run ${{ matrix.images }}